### ISSUE TITLE
Error when installing dsa5-drag-rule

### ISSUE THREAD

**Issue by br00n0** [Rapunzel77/dsa5-drag-ruler#2]
When trying to install, red error message appears:
![image](https://user-images.githubusercontent.com/79856383/191562422-87f6df8c-f01a-47f3-b6d9-edf369c2947e.png)

**Comment by br00n0** [comment]
drag-ruler v1.12.8
socketlib v1.0.11
foundry v10.286

**Comment by Rapunzel77** [comment]
confirmed

**Comment by Rapunzel77** [comment]
Fixed typo in download URL. 
Thanks for the report.
