### ISSUE TITLE
Version 1.10.1 does not install

### ISSUE THREAD

**Issue by br00n0** [Rapunzel77/dsa5-drag-ruler#3]
When updating modules, I get this manifest change popup:
![image](https://user-images.githubusercontent.com/79856383/192609259-2d172773-fb27-4b21-886d-9ef08915b13b.png)

After pressing Yes, I get this: 
![image](https://user-images.githubusercontent.com/79856383/192609448-5093afaf-9db7-4a76-abe1-30958cbe52cc.png)

And version remains at 1.10.0, no upgrade is ever made. I can repeat the steps all over again and nothing changes, even after uninstalling the underlying drag ruler and socketlib moduels.

Foundry VTT v10.286
dsa5-drag-ruler v1.10.0
foundryvtt-drag-ruler v1.12.8
foudryvtt-socketlib v1.0.11

**Comment by Rapunzel77** [comment]
Sorry for the late response this was a bit tricky to figure out. I seem to have messed up the version name. Interestingly I do not have this issue - so this is just a wild guess. I will update to a new version just to have that correct.

**Comment by Rapunzel77** [comment]
What I mean is that Version 10.0.1 has the version string of 10.0.0 which likely messes things up.

**Comment by Rapunzel77** [comment]
fixed this in the new version which is verified for current DragRuler release (and not only pre-release hotfix
If you still have this issue please reopen.
