### ISSUE TITLE
V12 update

### ISSUE THREAD

**Issue by Ginkgo85** [Rapunzel77/dsa5-drag-ruler#5]
Will it also get a v12 update?

**Comment by Rapunzel77** [comment]
yes it will. I have done some preliminary tests and all is looking good. I am just waiting for drag ruler to be available for v12. Currently that is not working, but an update has been announced: https://github.com/manuelVo/foundryvtt-drag-ruler/issues/326#issuecomment-2148372052

**Comment by Rapunzel77** [comment]
There is a beta release I'll check and add compatibility:
https://github.com/TPNils/foundryvtt-drag-ruler/releases/tag/1.13.8-beta

**Comment by Rapunzel77** [comment]
Created updated version that works well with the given beta release (hex grid seems to still be broken in drag ruler). 
https://discord.com/channels/170995199584108546/648215359895240715/1261622639126909008
This update should support the future release of drag-ruler as well as any compatible releases from forks like done by TPNils.
