### ISSUE TITLE
Drag Ruler put now  v12

### ISSUE THREAD

**Issue by Ginkgo85** [Rapunzel77/dsa5-drag-ruler#6]
Finally Dragruler is out and you can fully customize it ;-)

**Comment by Rapunzel77** [comment]
Indeed. In anticipation that the API won't change I already released the integration for v12 a while back using the "beta version"(there was a pull request that fixed things)  of drag ruler for testing. 
Now coming back everything is working very nicely with the released version for the integration. The things I mainly need to look out for are changes in TDE or FVTT anyhow.

I am a bit uncertain how to close this ticket, as it has no clear question, bug or feature request...
